import { useEffect, useState } from 'react'
import apiClient from '../api/client'
import { useAuth } from '../hooks/useAuth'

export default function StudentDashboard({ navigate }) {
  const { user } = useAuth(); const [courses, setCourses] = useState([]); const [sessions, setSessions] = useState([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { Promise.all([apiClient.get('/api/courses'), apiClient.get('/api/viva/sessions')]).then(([c, s]) => { setCourses(c.data); setSessions(s.data) }).catch((e) => setError(e.userMessage || 'Could not load your workspace.')).finally(() => setLoading(false)) }, [])
  return <main className="page-shell"><div className="welcome-row"><div><p className="eyebrow">STUDENT WORKSPACE</p><h1>Good to see you, {user?.full_name?.split(' ')[0] || 'there'}.</h1><p className="muted">Choose a course and get comfortable explaining what you know.</p></div><button className="button primary" onClick={() => navigate('/viva')}>Start a practice viva <span aria-hidden="true">↗</span></button></div>{error && <div className="notice error-text" role="alert">{error}</div>}{loading ? <p className="muted">Loading your courses…</p> : <><section><div className="section-heading"><div><p className="eyebrow">YOUR LEARNING</p><h2>Available courses</h2></div><span className="count-pill">{courses.length} courses</span></div>{courses.length ? <div className="course-grid">{courses.map((course, i) => <article className="course-card" key={course.id}><div className="course-art">0{i + 1}</div><span className="course-code">{course.code}</span><h3>{course.name}</h3><p>{course.description || 'Build confidence through a focused oral practice session.'}</p><div className="course-bottom"><span>{course.topics?.length || 0} topics</span><button className="text-button" onClick={() => navigate('/viva')}>Practice <span aria-hidden="true">→</span></button></div></article>)}</div> : <div className="empty-state"><h3>No courses available yet</h3><p>Ask your teacher to add course material before starting a viva.</p></div>}</section><section className="recent-section"><div className="section-heading"><div><p className="eyebrow">KEEP YOUR MOMENTUM</p><h2>Recent practice</h2></div></div>{sessions.length ? <div className="session-list">{sessions.slice(0, 5).map((s) => <div className="session-row" key={s.id}><div><strong>Practice session</strong><span>{new Date(s.started_at || Date.now()).toLocaleDateString()} · {s.status}</span></div>{s.status === 'completed' && <button className="text-button" onClick={() => navigate(`/report/${s.id}`)}>View report →</button>}</div>)}</div> : <p className="muted">Your completed sessions and feedback will appear here.</p>}</section></>}</main>
}
