import { useEffect, useState } from 'react'
import apiClient from '../api/client'
export default function TeacherDashboard({ navigate }) {
  const [sessions, setSessions] = useState([]); const [courses, setCourses] = useState([]); const [filter, setFilter] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { Promise.all([apiClient.get('/api/teacher/sessions'), apiClient.get('/api/courses')]).then(([s,c]) => { setSessions(s.data); setCourses(c.data) }).catch((e) => setError(e.userMessage || 'Could not load sessions.')).finally(() => setLoading(false)) }, [])
  const exportCsv = async () => { try { const { data } = await apiClient.get('/api/reports/export', { params: { course_id: filter || undefined }, responseType: 'blob' }); const url = URL.createObjectURL(data); const a = document.createElement('a'); a.href=url; a.download='viva-sessions.csv'; a.click(); URL.revokeObjectURL(url) } catch (e) { setError(e.userMessage || 'CSV export is unavailable.') } }
  const visible = sessions.filter((s) => !filter || s.course_id === filter)
  return <main className="page-shell"><div className="welcome-row"><div><p className="eyebrow">TEACHER WORKSPACE</p><h1>Review the thinking.</h1><p className="muted">Track practice sessions and give students clear next steps.</p></div><button className="button secondary" onClick={exportCsv}>↓ Export CSV</button></div>{error && <p className="error-text" role="alert">{error}</p>}<section className="table-card"><div className="section-heading"><div><p className="eyebrow">SESSION OVERVIEW</p><h2>Student sessions</h2></div><label className="filter-label">Course<select aria-label="Filter sessions by course" value={filter} onChange={(e) => setFilter(e.target.value)}><option value="">All courses</option>{courses.map(c => <option value={c.id} key={c.id}>{c.name}</option>)}</select></label></div>{loading ? <p className="muted">Loading sessions…</p> : visible.length ? <div className="session-list">{visible.map((s) => <div className="session-row" key={s.id}><div><strong>{s.student_name || 'Student'}</strong><span>{s.course_name} · {new Date(s.created_at).toLocaleString()}</span></div><span className={`status-tag ${s.status}`}>{s.status}</span><span className="session-score">{s.total_score == null ? '—' : `${Math.round(s.total_score * 100)}%`}</span><button className="text-button" onClick={() => navigate(`/review/${s.id}`)}>Review →</button></div>)}</div> : <div className="empty-state"><h3>No sessions to review</h3><p>Completed student viva sessions will appear here.</p></div>}</section><section className="teacher-tools"><article><span className="eyebrow">CONTENT</span><h3>Question banks</h3><p>Review and manage questions across your course topics.</p><button className="text-button" onClick={() => navigate('/questions')}>Open question bank →</button></article><article><span className="eyebrow">COURSES</span><h3>{courses.length} active courses</h3><p>Session reporting is grouped by course and student.</p></article></section></main>
}
